name: Validate Configs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.5'

      - name: Install dependencies
        run: |
          npm install typescript-json-schema ajv-cli

      - name: Generate JSON schema with typescript-json-schema
        run: |
          npx typescript-json-schema index.d.ts DeploymentConfig --noExtraProps --required --out config.schema.json

      - name: Validate all configs with ajv-cli
        run: |
          npx ajv validate -s config.schema.json -d "configs/*.json"
